version: '3'

services:
  postgres:
    # user: "${UID}:${GID}"
    build:
      context: .docker/postgres/
    command: postgres -c shared_preload_libraries='pg_stat_statements' #  -c logging_collector=on -c log_destination=stderr -c log_directory=/logs 
    restart: always
    environment:
      POSTGRES_USER: tonehub
      POSTGRES_PASSWORD: tonehub
      POSTGRES_DB: tonehub
      PGDATA: /pg-data
    ports:
      - "5432:5432"
    volumes:
      - ../var/docker/postgres/pg-data:/pg-data # ./var leads to ef permission exception
  adminer:
    image: adminer
    restart: always
    ports:
      - 4321:8080